src/Entity/ControleTech.php
<?php

namespace App\Entity;

use App\Repository\ControleTechRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ControleTechRepository::class)]
class ControleTech
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(length: 255)]
    private ?string $miseCirculation = null;

    #[ORM\ManyToOne(inversedBy: 'controleTeches')]
    private ?Detenteur $numPlaque = null;

    #[ORM\Column(length: 255)]
    private ?string $numChassis = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_delivrance = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_expiration = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getMiseCirculation(): ?string
    {
        return $this->miseCirculation;
    }

    public function setMiseCirculation(string $miseCirculation): static
    {
        $this->miseCirculation = $miseCirculation;

        return $this;
    }

    public function getNumPlaque(): ?Detenteur
    {
        return $this->numPlaque;
    }

    public function setNumPlaque(?Detenteur $numPlaque): static
    {
        $this->numPlaque = $numPlaque;

        return $this;
    }

    public function getNumChassis(): ?string
    {
        return $this->numChassis;
    }

    public function setNumChassis(string $numChassis): static
    {
        $this->numChassis = $numChassis;

        return $this;
    }

    public function getDateDelivrance(): ?\DateTimeInterface
    {
        return $this->date_delivrance;
    }

    public function setDateDelivrance(\DateTimeInterface $date_delivrance): static
    {
        $this->date_delivrance = $date_delivrance;

        return $this;
    }

    public function getDateExpiration(): ?\DateTimeInterface
    {
        return $this->date_expiration;
    }

    public function setDateExpiration(\DateTimeInterface $date_expiration): static
    {
        $this->date_expiration = $date_expiration;

        return $this;
    }
}

src/Form/ControleTechType.php
<?php

namespace App\Form;

use App\Entity\ControleTech;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ControleTechType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marque')
            ->add('type')
            ->add('modele')
            ->add('miseCirculation')
            ->add('numChassis')
            ->add('date_delivrance')
            ->add('date_expiration')
            ->add('numPlaque')
            ->add('editer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ControleTech::class,
        ]);
    }
}

src/Controller/ControleTechController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\ControleTech;
use Doctrine\Persistence\ManagerRegistry;
use App\Form\ControleTechType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class ControleTechController extends AbstractController
{
    #[Route('/controleTech', name: 'controleTech')]
    public function controleTech(EntityManagerInterface $entityManager): Response
    {
        $controleTechs = $entityManager->getRepository(ControleTech::class)->findAll();

        return $this->render('controle_tech/controleTech.html.twig', ['controleTechs' => $controleTechs]);
    }

    #[Route('/editerControleTech/{id?0}', name: 'editerControleTech')]
    public function editerControleTech(ControleTech $controleTech = null, ManagerRegistry $doctrine, Request $request): Response
    {
        $new = false;
        if(!$controleTech){
            $new = true;
            $controleTech = new ControleTech();
        }

        $form = $this->createForm(ControleTechType::class, $controleTech);
        $form->handleRequest($request);

        if($form->isSubmitted()){

            $manager = $doctrine->getManager();
            $manager->persist($controleTech);

            $manager->flush();

            if($new){
                $message = "Le control a été ajouter avec succès";
            }else{
                $message = "Me control a été editer avec succès";
            }

            $this->addFlash("succes", $message);

            return $this->redirectToRoute("controleTech");
        }else{
            return $this->render('controle_tech/addControleTech.html.twig', [
                'form' => $form->createView()
            ]);
        }
    }

    #[Route('/detailControleTech/{id?0}', name: 'detailControleTech')]
    public function detailControleTech(ManagerRegistry $doctrine, ControleTech $controleTech = null ): Response
    {
        if(!$controleTech){
            $this->addFlash('error', "Ce détenteur n'existe pas !");
            return $this->redirectToRoute("detenteurs");
        }
        return $this->render('controle_tech/detailControlTech.html.twig', ['controleTech' => $controleTech]);
    }

    #[Route('/deleteControleTech/{id?0}', name: 'deleteControleTech')]
    public function deleteControleTech(ControleTech $controleTech = null, ManagerRegistry $doctrine, $id): Response
    {

        $repository = $doctrine->getRepository(ControleTech::class);
        $controleTech = $repository->find($id);

        $manager = $doctrine->getManager();
        $manager->remove($controleTech);

        $manager->flush();

        $message = " a été supprimer avec succès";


        $this->addFlash("succes", $controleTech->getPrenom() . $message);

        return $this->redirectToRoute("controleTech");

    }

}

templates/controle_tech/addControleTech.html.twig
 {% extends 'template.html.twig' %}

{% block title %} Controller | Controlle Technique {% endblock %}

{% block body %}
 
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Formulaire d'ajout de Controlle Technique</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Formulaire</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Ajouter Un controlle</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              {{ form_start(form) }}
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.numPlaque) }}
                                {{ form_widget(form.numPlaque, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez le numero de la plaque'
                                }}) }}
                                
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.marque) }}
                                {{ form_widget(form.marque, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez la marque'
                                }}) }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.type) }}
                                {{ form_widget(form.type, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez le type'
                                }}) }}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.modele) }}
                                {{ form_widget(form.modele, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez votre le modele'
                                }}) }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.miseCirculation) }}
                                {{ form_widget(form.miseCirculation, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez la mise en circulation'
                                }}) }}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.numChassis) }}
                                {{ form_widget(form.numChassis, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez le numéro de la chassis'
                                }}) }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.date_delivrance) }}
                                {{ form_widget(form.date_delivrance, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez la date'
                                }}) }}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                {{ form_label(form.date_expiration) }}
                                {{ form_widget(form.date_expiration, {'attr': {
                                    'class':'required form-control',
                                    'placeholder' : 'Entrez le daate'
                                }}) }}
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer"> 
                    {{ form_widget(form.editer, {'attr': {'class':'btn btn-primary'}}) }}
                </div>
              
            </div>
            <!-- /.card -->

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  
{% endblock %}

templates/controle_tech/controleTech.html.twig
{% extends 'template.html.twig' %}

{% block title %} Controller | Controlle Technique {% endblock %}

{% block body %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Liste des Controlles Techniques</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Controlle Technique</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- /.row -->
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Liste des controlles techniques</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Num Plaque</th>
                      <th>Marque</th>
                      <th>Type</th>
                      <th>Modèle</th>
                      <th>Mise en circulation</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for controleTech in controleTechs %}
                      <tr>
                        <td>{{ controleTech.numPlaque }}</td>
                        <td>{{ controleTech.marque }}</td>
                        <td>{{ controleTech.type }}</td>
                        <td><span class="tag tag-success">{{ controleTech.modele }}</span></td>
                        <td>{{ controleTech.miseCirculation }}</td>
                        <td>
                          <div class="row">
                            <div class="col-4">
                              <a href="{{ path('detailControleTech', {id:controleTech.id}) }}" class="btn btn-block btn-outline-success">Voir</a>
                            </div>
                            <div class="col-4">
                              <a href="{{ path('editerControleTech', {id: controleTech.id}) }}" class="btn btn-block btn-outline-info">Modif</a>
                            </div>
                            <div class="col-4">
                              <a href="{{ path('deleteControleTech', {id: controleTech.id}) }}" class="btn btn-block btn-outline-danger">Suppr</a>
                            </div>
                          </div>
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <div class="col-2">
            <a href="{{ path('editerControleTech') }}" class="btn btn-block btn-primary">Ajouter</a>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
 
  {% endblock %}

templates/controle_tech/detailControlTech.html.twig
{% extends 'template.html.twig' %}

{% block title %} Controller | Detail Controle Technique {% endblock %}

{% block body %}

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Controle Technique Detail</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Controle Technique</a></li>
              <li class="breadcrumb-item active">Controle Technique Detail</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Controle Technique Detail</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
              <div class="row">
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Plaque</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ controleTech.numplaque }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Marque</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ controleTech.marque }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Type</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ controleTech.type }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-6">
                  <h4>Details du Controle Technique</h4>
                    <div class="post">
                      <div class="user-block">
                        <span class="username">
                          <a href="#">{{ controleTech.marque }} {{ controleTech.modele }}</a>
                        </span>
                        <span class="description">{{ controleTech.type }}</span>
                      </div>
                      <!-- /.user-block -->
                      <div class="row">
                        <div class="col-6">
                            <p>
                                <p>Marque du véhicule : {{ controleTech.marque }}</p>
                                <p>Modèle du véhicule : {{ controleTech.modele }}</p>
                                <p>Mise en circulation : {{ controleTech.miseCirculation }}</p>
                                <p>Numéro de la plaque : {{ controleTech.numPlaque }}</p>
                                <p>Numéro de la Chassis : {{ controleTech.numChassis }}</p>
                                <p>Date de délivrance : {{ controleTech.dateDelivrance|date('d/m/Y') }}</p>
                                <p>Date d'expiration : {{ controleTech.dateExpiration|date('d/m/Y') }}</p> 
                            </p>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
              <h3 class="text-primary"><i class="fas fa-paint-brush"></i> {{ controleTech.marque }} {{ controleTech.modele }}</h3>
              <p class="text-muted">{{ controleTech.marque }} {{ controleTech.type }}</p>
              <br>
              <div class="text-muted">
                <p class="text-sm">Numéro de la Plaque
                  <b class="d-block">{{ controleTech.numPlaque }}</b>
                </p>
                <p class="text-sm">Mise en circulation
                  <b class="d-block">{{ controleTech.miseCirculation }}</b>
                </p>
                <p class="text-sm">Date de délivrance
                  <b class="d-block">{{ controleTech.dateDelivrance|date('d/m/Y') }}</b>
                </p>
                <p class="text-sm">Date d'expiration
                  <b class="d-block">{{ controleTech.dateExpiration|date('d/m/Y') }}</b>
                </p>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



  {% endblock %}